/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_royole_ekulelu_jnitest_JNIUtil */

#ifndef _Included_com_royole_ekulelu_jnitest_JNIUtil
#define _Included_com_royole_ekulelu_jnitest_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_royole_ekulelu_jnitest_JNIUtil
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_royole_ekulelu_jnitest_JNIUtil_getStringFormC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
